# Streamlit Secrets f√ºr lokale Installation

[api]
api_key = "ef8c2eb9be6b43fe8353c99f51904c0f"
weather_key = "de6b12b5cd22b2a20761927a3bf39f34"
api_football_key = "1a1c70f5c48bfdce946b71680e47e92e"
